### ISSUE TITLE
Difference between no-skipped-tests and no-disabled-tests?

### ISSUE THREAD

**Issue by nmay231** [veritem/eslint-plugin-vitest#109]
As the title states, is there a difference between `no-skipped-tests` and `no-disabled-tests`?

If yes, it should be documented more clearly (I'm willing to help with that).

If not, should one be deprecated in favor of the other?

**Comment by veritem** [comment]
@nmay231 sorry, so `no-skipped-tests` was an initial attempt to write `no-disabled-tests`. I'm going to remove it in the next version.
