### ISSUE TITLE
Generate docs file for each rule?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [veritem/eslint-plugin-vitest#15]
It'd be nice to have at least a `.md` docs file describing each rule. It's easier to read rule docs that way.

https://github.com/bmish/eslint-doc-generator exists and is great for setting up eslint plugin repo scaffolding. Would you accept a PR that adds it in here? 😁

**Comment by veritem** [comment]
ooh yeah, haven't thought about adding `.md` docs before. Of course, PR would be appreciated 👍
