### ISSUE TITLE
valid-title schema cannot be processed by jsonschema

### ISSUE THREAD

**Issue by Shinigami92** [veritem/eslint-plugin-vitest#156]
https://github.com/veritem/eslint-plugin-vitest/blob/7f86917a5ae217a2f96efced6a47577362f9235c/src/rules/valid-title.ts#L127-L141

This part cannot be correctly read and processed by `json-schema-to-typescript`'s compile

This results in the need of applying a diff when generating the supportive `eslint-define-config` file
https://github.com/Shinigami92/eslint-define-config/blob/main/scripts/generate-rule-files/diffs/rules/vitest/valid-title.d.ts.diff

**Comment by veritem** [comment]
that's an interesting project. I'll see if i can type this better.

**Comment by veritem** [comment]
hey @Shinigami92 is this still an issue?

**Comment by Shinigami92** [comment]
> hey @Shinigami92 is this still an issue?

the structure of eslint-define-config changed with v2
so now vitest would need to ship its own type-suport
