### ISSUE TITLE
meta: is prettier used?

### ISSUE THREAD

**Issue by sapphi-red** [veritem/eslint-plugin-vitest#162]
`pnpm format` is declared in `package.json`.
https://github.com/veritem/eslint-plugin-vitest/blob/a930a2cd81141c57b116621b0107d42b1fb4eeb7/package.json#L30-L31

But when I run this command many files gets changed. Is this used? (the config is lacking?) or should the command be removed?

**Comment by veritem** [comment]
this command should be removed. I used prettier a while a go and removed it some time a go. Will push an update about this.
