### ISSUE TITLE
Set rules to error by default instead of warning

### ISSUE THREAD

**Issue by Shinigami92** [veritem/eslint-plugin-vitest#167]
Related to https://github.com/faker-js/faker/pull/2098#issuecomment-1537238525

We are requesting to set the rules to `error` instead of `warning` in the `plugin:vitest/recommended` and `plugin:vitest/all`, because running lint in CI does not trigger any failures and so it only pollutes the logs and nobody cares and just ignores the warnings.

If someone explicitly want to only use `warn` for a rule, _because of any reason_, they should override or define their own set.

- [x] I'm willing to do a PR, if the requested changes gets accepted

If the request gets not excepted, please document a reason `why` it was decided to use `warn` over `error` in the README.md

**Comment by ST-DDT** [comment]
Eslint itself also only uses error for their recommendations:

https://github.com/eslint/eslint/blob/main/packages/js/src/configs/eslint-recommended.js

**Comment by veritem** [comment]
Hey, I didn't think through this enough when building this. Setting warning for recommeded makes sense to me. Give me a sec as i publish a new version.

**Comment by veritem** [comment]
Should be release as a part of 0.2.0. Thanks for reporting this :)

**Comment by Shinigami92** [comment]
You also might want to update the README

**Comment by veritem** [comment]
goo catch! thanks
