### ISSUE TITLE
Add `plugin:vitest/strict`

### ISSUE THREAD

**Issue by ahnpnl** [veritem/eslint-plugin-vitest#168]
Hi,

Thank you for your effort on this repo. Is it possible we can have `plugin:vitest/strict` which set `error` instead of `warn` next to the existinng `plugin:vitest/recommended`?

**Comment by veritem** [comment]
current version (0.2.0) `error` instead of `warning` for recommended rules. I didn't think through it when i started working on the project but having error instead of warning makes sense. Give it a try and thanks for opening this issue :)
