### ISSUE TITLE
How about convert the whole title into lowercase when using prefer-lowercase-title?

### ISSUE THREAD

**Issue by so1ve** [veritem/eslint-plugin-vitest#189]
For example:
```ts
describe('SFC compile', () => {})
```

The rule will convert it to `sFC compile`, which is pretty ugly. I think `sfc compile` is better.

**Comment by veritem** [comment]
this rule only converts the first letter of title. It was create this way since some that's how jest-eslint-plugin works. I would love to lower case the whole title by the way. If we can lower case all letters and make sure we cover all edge cases that's would be great.

**Comment by so1ve** [comment]
Shall we add an option?

**Comment by veritem** [comment]
definitely
