### ISSUE TITLE
bug: shareable configs don't work with eslint's new "flat" config

### ISSUE THREAD

**Issue by michaelfaith** [veritem/eslint-plugin-vitest#215]
I searched through the issues for something similar, and didn't find anything related to supporting the new [Flat Config](https://eslint.org/docs/latest/use/configure/configuration-files-new).  So I thought it would make sense to create this for tracking.

I'm currently building out a config using `eslint.config.js` and the new flat config structure.  When using this plugin's shareable config 
```js
import vitest from 'eslint-plugin-vitest';

export default [
  vitest.configs.recommended,
];
```

I receive the following error:
```bash
TypeError: Key "plugins": Key "0": Expected an object.
    at Object.validate (D:\src\ux\.yarn\cache\eslint-npm-8.45.0-bb6c5f1226-3e6dcce5cc.zip\node_modules\eslint\lib\config\flat-config-schema.js:315:23)
    at ObjectSchema.validate (D:\src\ux\.yarn\cache\@humanwhocodes-object-schema-npm-1.2.1-43b3ca2646-a824a1ec31.zip\node_modules\@humanwhocodes\object-schema\src\object-schema.js:218:35)
    at D:\src\ux\.yarn\cache\@humanwhocodes-object-schema-npm-1.2.1-43b3ca2646-a824a1ec31.zip\node_modules\@humanwhocodes\object-schema\src\object-schema.js:171:18
    at Array.reduce (<anonymous>)
    at ObjectSchema.merge (D:\src\ux\.yarn\cache\@humanwhocodes-object-schema-npm-1.2.1-43b3ca2646-a824a1ec31.zip\node_modules\@humanwhocodes\object-schema\src\object-schema.js:169:24)
    at D:\src\ux\.yarn\cache\@humanwhocodes-config-array-npm-0.11.10-33012f902e-1b1302e240.zip\node_modules\@humanwhocodes\config-array\api.js:916:42
    at Array.reduce (<anonymous>)
    at FlatConfigArray.getConfig (D:\src\ux\.yarn\cache\@humanwhocodes-config-array-npm-0.11.10-33012f902e-1b1302e240.zip\node_modules\@humanwhocodes\config-array\api.js:915:39)
    at FlatConfigArray.isFileIgnored (D:\src\ux\.yarn\cache\@humanwhocodes-config-array-npm-0.11.10-33012f902e-1b1302e240.zip\node_modules\@humanwhocodes\config-array\api.js:943:15)
    at D:\src\ux\.yarn\cache\eslint-npm-8.45.0-bb6c5f1226-3e6dcce5cc.zip\node_modules\eslint\lib\eslint\eslint-helpers.js:312:49
```

This is due to the fact that the shareable config defines `plugins` as a string array, rather than object: 
https://github.com/veritem/eslint-plugin-vitest/blob/d55e5b0bdb1ceb45c8ed282fb3b0250c8f93e05a/src/index.ts#L51-L59

I'm able to work around it by constructing the config manually using the recommended rules and globals:
```js
import vitest from 'eslint-plugin-vitest';

export default [
  {
    plugins: { vitest },
    rules: vitest.configs.recommended.rules,
    languageOptions: {
      globals: vitest.environments.env.globals,
    }
  },
];
```

But ideally this would be built-in to the shareable configs.
The `eslint-plugin-react` and `eslint-plugin-jsdoc` projects have updated to support this new config approach, if that helps with providing inspiration / examples.

Repro: https://github.com/michaelfaith/eslint-plugin-vitest-flat-config-bug

**Comment by veritem** [comment]
@michaelfaith do you have an example repo or a codesand box where i can play with your example? I would like to add support for this but also not break anything.

**Comment by michaelfaith** [comment]
@veritem I don't at the moment, but I can create one.  If you already have a test repo, it would just be a matter of changing the config file name from .eslintrc to eslint.config.js and using something like this: 

```js
import vitest from 'eslint-plugin-vitest';

export default [
  vitest.configs.recommended,
];
```

Eslint is looking for the file name `eslint.config.js` to trigger handling the new config format.

**Comment by michaelfaith** [comment]
@veritem I went ahead and created a repro based on the `fixtures` project in your repo:  https://github.com/michaelfaith/eslint-plugin-vitest-flat-config-bug

Appreciate the attention on this.  Let me know if you need any additional details from me.

**Comment by veritem** [comment]
Seems like my work around didn't fix your issue. I'll look more into it later.

**Comment by veritem** [comment]
check readme for an example config

**Comment by michaelfaith** [comment]
> check readme for an example config

Hey, maybe I'm missing something, but I don't see any mention of the flat config set up.  The closest I see is this, which looks like it may be what you mean, but the flat config doesn't use `eslintrc` files.  The file name has to be `eslint.config.js`.  So, may need a minor tweak to that, if that was the intent?

> If you're using `.eslintrc.js`
> 
> ```js
> import vitest from "eslint-plugin-vitest";
> 
> export default [
>   {
>     files: ["tests/**"], // or any other pattern
>     plugins: {
>       vitest,
>     },
>     rules: {
>       ...vitest.configs.recommended.rules,
>     },
>     languageOptions: {
>       globals: {
>         ...vitest.environments.env.globals,
>       },
>     },
>   },
> ];
> ```

And, while that's a good work around for the current set up, do you anticipate that you'll fully embrace the flat config structure at some point?

**Comment by veritem** [comment]
a pr is welcome
