### ISSUE TITLE
Add a 'recommended' ruleset?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [veritem/eslint-plugin-vitest#22]
A lot of ESLint plugins provide a 'recommended' ruleset so folks don't have to manually enable most of their rules. Would you accept a PR for one here?

A couple examples:

* https://typescript-eslint.io/linting/configs#recommended
* https://github.com/mysticatea/eslint-plugin-node#-configs

**Comment by SalahAdDin** [comment]
> A lot of ESLint plugins provide a 'recommended' ruleset so folks don't have to manually enable most of their rules. Would you accept a PR for one here?
> 
> A couple of examples:
> 
>     * https://typescript-eslint.io/linting/configs#recommended
> 
>     * https://github.com/mysticatea/eslint-plugin-node#-configs

Yeah, just i was looking at it, but you commented first.

You are pretty right.

**Comment by AriPerkkio** [comment]
If this gets accepted, I would recommend to add an `all` configuration as well. That one could be a private undocumented API - I think `eslint-plugin-unicorn` does that. 

It could be used here if #28 gets accepted: https://github.com/veritem/eslint-plugin-vitest/pull/28/files#diff-c9b7db67d51aa1a4ed29166670b8125379863f5e649c132dfdd7dec0649f6c7dR34-R37

**Comment by veritem** [comment]
> A lot of ESLint plugins provide a 'recommended' ruleset so folks don't have to manually enable most of their rules. Would you accept a PR for one here?
> 
> A couple examples:
> 
> * https://typescript-eslint.io/linting/configs#recommended
> * https://github.com/mysticatea/eslint-plugin-node#-configs

PRs are always welcome.

**Comment by veritem** [comment]
Recommended rules is currently added in the latest release.

**Comment by JoshuaKGoldberg** [comment]
🙌 thanks!
