### ISSUE TITLE
Bug: Vitest eslint rules are applied to non testing files

### ISSUE THREAD

**Issue by SalahAdDin** [veritem/eslint-plugin-vitest#224]
Thanks for this useful hook,

It seems ESLint is applying these package rules for all the files and not only to the testing files:
![image](https://github.com/veritem/eslint-plugin-vitest/assets/5034215/68822959-9cce-4269-8408-69f2d8366e84)

The rule applied here is [this,](https://github.com/veritem/eslint-plugin-vitest/blob/main/docs/rules/require-hook.md) and it shows examples only for testing files, so it should be applied only to the testing files.

For fixing this we can use the[ `overrides` keyword from **eslint**](https://eslint.org/docs/latest/use/configure/configuration-files#how-do-overrides-work), but it should come like this by default, as other packages do.

Thanks!

**Comment by veritem** [comment]
thanks, this is a bug. I'll fix it.

**Comment by veritem** [comment]
@SalahAdDin  did you try using this rule https://github.com/veritem/eslint-plugin-vitest/blob/main/docs/rules/consistent-test-filename.md . would you mind sharing a repro of your issue?

**Comment by SalahAdDin** [comment]
> @SalahAdDin did you try using this rule https://github.com/veritem/eslint-plugin-vitest/blob/main/docs/rules/consistent-test-filename.md . would you mind sharing a repro of your issue?

That rule check if the test files' names are correct or not, it does not scope the testing rules to testing files, as far as I understand.

**Comment by veritem** [comment]
@SalahAdDin would you mind sharing a code repo I can play around for this?

**Comment by SalahAdDin** [comment]
This one is my project template: https://github.com/SalahAdDin/react-ts-vite-template

**Comment by veritem** [comment]
You have to make a few changes in your `.eslintrc`. I've made a [pr](https://github.com/SalahAdDin/react-ts-vite-template/pulls) on your repo with config that works . I have also improved [docs](https://github.com/veritem/eslint-plugin-vitest#running-on-test-files-only)

**Comment by SalahAdDin** [comment]
> You have to make a few changes in your `.eslintrc`. I've made a [pr](https://github.com/SalahAdDin/react-ts-vite-template/pulls) on your repo with config that works . I have also improved [docs](https://github.com/veritem/eslint-plugin-vitest#running-on-test-files-only)

Man, you wouldn't have bothered, thanks a lot, I'll keep an eye on it!
