### ISSUE TITLE
valid-type: use type checking to determine test name type?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [veritem/eslint-plugin-vitest#251]
I noticed that the `valid-title` rule doesn't use [typed linting](https://typescript-eslint.io/linting/typed-linting) to determine whether a title is a string (or, pending #247, a function). It just goes off the AST node type. That means dynamic nodes such as Identifiers will always be detected as non-strings:

```js
let nameBase = "My name: ";

const makeName = (suffix: string) => `first ${suffix}`;

describe(makeName("second"), () => { /* ... */ } /*
~~~~~~~~ */
// Test title must be a string.
```

What is your viewpoint on enabling typed linting (https://typescript-eslint.io/developers/custom-rules#typed-rules)? It would be a breaking change for existing users and have configuration (https://typescript-eslint.io/linting/typed-linting#specifying-tsconfigs / https://typescript-eslint.io/linting/typed-linting/monorepos) & performance (https://typescript-eslint.io/linting/typed-linting#how-is-performance) implications. But I think this is effectively a blocker for #247?

Note that we recommend against rules "progressively enhancing" with type information (except if there's an explicit option): https://github.com/typescript-eslint/typescript-eslint/pull/7440 -> https://github.com/typescript-eslint/typescript-eslint/pull/7440#discussion_r1319304905

**Comment by so1ve** [comment]
If these rules requires type information, this will become a breaking change. I prefer implementing it in a separate plugin. (Maybe `eslint-plugin-vitest-typechecked`? :P)

**Comment by veritem** [comment]
I don't think it should be necessary a different package. I feel like if we bump another version people will stick to whatover they like.  Josh, I'll look into this over fall break.

**Comment by so1ve** [comment]
Maybe introduce a new option "typecheck"?
