### ISSUE TITLE
Necessary to have TypeScript as dependency ? 

### ISSUE THREAD

**Issue by MaximeGrimler** [veritem/eslint-plugin-vitest#264]
Hello,

Is it necessary to have TypeScript as dependency ? https://github.com/veritem/eslint-plugin-vitest/blob/main/package.json#L80

Wouldn't it be better to have it as peerDependency or devDependency ? Because by putting it as dependency it's included into the list and can be duplicated if we don't have the same range as defined by the one defined in the package.json ...

Thanks!

**Comment by veritem** [comment]
I have been working on typed rules and ended up having it along with other deps. Thank you for reminding me! We do not need to have typescript to use eslint-plugin-vitest.

**Comment by veritem** [comment]
I fixed this in the latest version.
