### ISSUE TITLE
expect-expect customExpressions regex

### ISSUE THREAD

**Issue by barrykaplan** [veritem/eslint-plugin-vitest#267]
Does this only take explicit name? When assertions are factored into to functions, where the name is unique to each, how can this be specified. A common prefix would be find. But I cannot seem to get any regex to work here.

```
    "vitest/expect-expect": [
      "error",
      {
        "customExpressions": [
          "expect",
          "expect.*"
        ]
      }
    ],
```

**Comment by gxxcastillo** [comment]
I'm finding that setting any value for `vitest/expect-expect` makes the rule stop working altogether.

For example this makes it so the rule stops working:

```
  rules: {
    'vitest/expect-expect': [
      'error',
      {
        customExpressions: ['expect'],
      },
    ],
  },
```

**Comment by gxxcastillo** [comment]
I've tried disabling `vitest/expect-expect` and enabling `jest/expect-expect` instead but it seems that so long as I have `vitest/expect-expect` set then the values I pass for `jest/expect-expect` are ignored.

**Comment by veritem** [comment]
please provide a repro for this issue I can't reproduce with current test cases.
