### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by pelletier197** [veritem/eslint-plugin-vitest#27]
I am getting an error that crashes eslint when the plugin tries to parse the following statement. 

```typescript 
    it('should update all file aggregations then all scans', () => {
      fileAggregationRepositoryMock.verify((x) => x.updateAllFileAggregations())
    })
```

This is the code block in question that causes the issue:

![image](https://user-images.githubusercontent.com/24528884/209222219-64629907-e012-4786-a650-dca8031f8aa8.png)

in the `expect-expect` rule

**Comment by cmolina** [comment]
This could be written as 

``` javascript
const hasExpect = args.some((arg) => {
  return arg.body.body?[0].expression?.callee.object.callee?.name === "expect";
});
```
