### ISSUE TITLE
Use a smaller error range for no-disabled-tests, just like for no-focused-tests

### ISSUE THREAD

**Issue by lydell** [veritem/eslint-plugin-vitest#270]
no-disabled-tests is very noisy because it underlines so much code:

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/2142817/137583039-c458e81e-66cf-4e71-a5a6-d32f1eb4c36b.png">

no-focused-tests is much nicer:

<img width="1100" alt="image" src="https://user-images.githubusercontent.com/2142817/137583055-54c726fd-b39d-48fb-88fe-9532549b7349.png">

**Comment by veritem** [comment]
a pr is welcome!
