### ISSUE TITLE
Mark vitest as an optional peer dependency with peerDependenciesMeta

### ISSUE THREAD

**Issue by ericmatthys** [veritem/eslint-plugin-vitest#283]
Similar to the reasoning in https://github.com/jest-community/eslint-plugin-jest/pull/970, a shareable ESLint config does not need to depend directly on vitest. For example, in a monorepo it's common to have a package that contains the ESLint config for the rest of the packages in the monorepo. This package has no need to depend on `vitest` except to satisfy peer dependency errors from `eslint-plugin-vitest`.

**Comment by veritem** [comment]
thanks! this should be fixed in latest version.
