### ISSUE TITLE
Favor `toHaveBeenCalledExactlyOnceWith`

### ISSUE THREAD

**Issue by C0ZEN** [veritem/eslint-plugin-vitest#297]
In the same style as https://github.com/veritem/eslint-plugin-vitest/blob/main/docs/rules/prefer-called-with.md, would it be possible to have a rule preferring using `toHaveBeenCalledExactlyOnceWith` over the usage of both `toHaveBeenCalledOnce` and `toHaveBeenCalledWith`?

**Comment by veritem** [comment]
mind sharing a reason why we should prefer `toHaveBeenCalledExactlyOnceWith`?

**Comment by C0ZEN** [comment]
I'm used to always do this in my tests:

```typescript
expect(x). toHaveBeenCalledOnce();
expect(x). toHaveBeenCalledWith(args);
```

And on a large scale, reducing this to:

```typescript
expect(x). toHaveBeenCalledExactlyOnceWith(args);
```

Would be slightly better.
So enforcing this as a linter rule would be nice to ensure consistency.
