### ISSUE TITLE
New rule: no-import-test-from-test

### ISSUE THREAD

**Issue by hornta** [veritem/eslint-plugin-vitest#303]
I want a rule that forbids me to import things in a testfile from another testfile.

In my `featureA.test.ts` I imported foo from `featureB.test.ts` which caused failing tests in featureB to appear in featureA in the vitest ui.

**Comment by veritem** [comment]
a PR is welcome!

**Comment by veritem** [comment]
I'm trying to think through this. @hornta How do you think we should check if a file is a test file?

**Comment by hornta** [comment]
If it contains a test/it declaration because it's only then my problem occurs.

**Comment by veritem** [comment]
will implement this if many people would like a linter todo it for them
