### ISSUE TITLE
"Cannot read properties of undefined (reading 'testTitles')", with vitest/no-identical-title and using fdescribe

### ISSUE THREAD

**Issue by pixelastic** [veritem/eslint-plugin-vitest#310]
Hello,

When using a custom `fdescribe` (which is an alias to `describe.focus`) in test files, the `no-identical-title` seem to choke and throw an error. It doesn't happen all the time, it seem to depend on the number of `fdescribe` in the file, but I made a simple reproduction case below:

---

```js
// test.js
fdescribe('a describe', () => {
  test('a test', () => {
    expect(true).toBe(true);
  });
});
fdescribe('another describe', () => {
  test('a test', () => {
    expect(true).toBe(true);
  });
});
```
```js
// eslint.cjs
module.exports = {
  parserOptions: {
    ecmaVersion: 'latest',
  },
  extends: [
    'plugin:vitest/recommended'
  ]
}
```

Running `yarn run vitest ./test.js` yields the following error:

```
TypeError: Cannot read properties of undefined (reading 'testTitles')
Occurred while linting /path/to/file/to/test.js:21
Rule: "vitest/no-identical-title"
```

---
## Context

I recently switched from Jest to Vitest. I added aliases in my `setupFiles` to map `globalThis.fdescribe` to `globalThis.describe.focus` (I did the same for `xdescribe`/`xit`/`fit`; I like the short syntax).

My tests run fine, the `fdescribe` are correctly focused, but the linter fails.

If I manually add a `const fdescribe = describe.only` at the top of my test file, the linting works correctly. Somehow it seems that the custom content of `globalThis` I added is not picked.

I see in `validVitestFnCallChains.ts` a mention of a `TODO` with `fdescribe` https://github.com/veritem/eslint-plugin-vitest/blob/main/src/utils/validVitestFnCallChains.ts#L1009-L1018 don't know if this is related or not.

**Comment by veritem** [comment]
should be fixed in next version. thanks for letting me know.
