### ISSUE TITLE
[Feature Request]: Add rule when using `.concurrent` and snapshots

### ISSUE THREAD

**Issue by Haberkamp** [veritem/eslint-plugin-vitest#311]
To run snapshot tests in parallel you must use the local Test Context. See: https://vitest.dev/api/#test-concurrent

Vitest already warns us about that once we write execute the test. (`Error: Snapshot cannot be used outside of test`). The error message does not tell the developer how to fix the issue. Adding a new lining rule will improve the developer experience for that scenario.

I'd be willing to contribute a PR for this issue.

**Comment by veritem** [comment]
a pr is welcome!
