### ISSUE TITLE
Remove `prefer-to-be` from Recommended Configuration

### ISSUE THREAD

**Issue by ahilke** [veritem/eslint-plugin-vitest#331]
# Summary

The rule `prefer-to-be` should not be enabled with the recommended rule set, as it is a stylistic and preference-based rule.

# Issue

Using `toBe()` over `toEqual` (or `toStrictEqual`) is not strictly better and there are good reasons to not use `prefer-to-be`. I prefer using `toEqual` for both primitives and objects, because it removes unnecessary nuance about when to use which. `toEqual` almost always does what I want, except for rare cases when I need to compare object references. For an article with a bit more depth, refer to https://dev.to/thejaredwilcurt/why-you-should-never-use-tobe-in-jest-48ca. 

The recommended ruleset should only contain rules that are almost always beneficial and prevent bugs. This is not the case for `prefer-to-be`. The best reasoning I could find for such a rule was purely stylistic, because "it reads better" (from https://github.com/jest-community/eslint-plugin-jest/issues/801). Note that `eslint-plugin-jest` does not include `prefer-to-be` in the recommended rule set, but the style rule set instead.

It would also help to add some reasoning to the rule to help people decide whether they should enable it or not - again, [similar to what `eslint-plugin-jest` does](https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/prefer-to-be.md):

> When asserting against primitive literals such as numbers and strings, the equality matchers all operate the same, but read slightly differently in code.
>
> This rule recommends using the toBe matcher in these situations, as it forms the most grammatically natural sentence. For null, undefined, and NaN this rule recommends using their specific toBe matchers, as they give better error messages as well.

**Comment by veritem** [comment]
I didn't have a specific reason of making `prefer-to-be` a recommended rule to be honest. You're reasoning made me think through it a bit more. I agree with you that it shouldn't be a recommended rule.

**Comment by ahilke** [comment]
Thank you! Appreciate the fast response
