### ISSUE TITLE
Remove `prefer-called-exactly-once-with` rule

### ISSUE THREAD

**Issue by davecardwell** [veritem/eslint-plugin-vitest#336]
#297 adds `prefer-called-exactly-once-with`, however `toHaveBeenCalledExactlyOnceWith` does not exist in Vitest:

https://github.com/search?q=repo%3Avitest-dev%2Fvitest%20%2FtoHaveBeenCalledExactlyOnceWith%2F&type=code

**Comment by veritem** [comment]
thanks for the feedback.
