### ISSUE TITLE
`expect-expect` - doesn't make much sense for skipped tests

### ISSUE THREAD

**Issue by Maxim-Mazurok** [veritem/eslint-plugin-vitest#339]
I have skipped `it.skip(...)` test without assertions, it's used mostly for debugging, etc.

Doesn't really make sense to enforce `expect-expect` rule for it IMO.

**Comment by veritem** [comment]
it errors out when the test is empty -- doesn't have any assertion. if there is not assertion you probably should delete that test.

**Comment by Maxim-Mazurok** [comment]
Well, you do want to have assertions in the tests that you're running, otherwise it's likely a mistake. However for tests that you're - skipping it doesn't seem that important. Since the test is skipped to begin with it doesn't have to be perfect. But then I guess the same applies to all other rules... Anyway, I ended up just ignoring the rule for the skipped test, thought that it may be a common issue, but if not I guess it doesn't warrant special treatment. Cheers!

**Comment by veritem** [comment]
pushed a fix on main
