### ISSUE TITLE
expect-expect doesn't factor in assert

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [veritem/eslint-plugin-vitest#345]
Is it intentional that [`vitest/expect-expect`](https://github.com/veritem/eslint-plugin-vitest/blob/426fc9295fe7ca17d90255f677b2505694e8c995/docs/rules/expect-expect.md) doesn't factor in calls to Vitest's `assert` to constitute having an expectation in the test body?

Minimum repro:

```js
import { assert, test } from "vitest";

test("", () => {
  assert.equal(1, 1);
});
```

Repro in a repo: https://github.com/JoshuaKGoldberg/create-typescript-app/blob/a8f6b233c5403b22f647febacbea6f3e5c57e125/script/migrate-test-e2e.js#L127

FWIW I'd consider this a bug. Given that Vitest re-exports Chai's `assert` function, I think enforcing using `assert` vs. `expect` is a separate lint rule concern from having any expectation in a test body. Maybe the rule should be renamed to `vitest/expect-expectation`?

**Comment by veritem** [comment]
the ethos for this rule is that it expects you to have `expect` in test body. this is an edge I haven't thought about when working on this rule. what you can do for now is adding `assert` in rule's `assertFunctionNames` option

**Comment by veritem** [comment]
@JoshuaKGoldberg let me know if this is still a broker for you

**Comment by JoshuaKGoldberg** [comment]
Thanks - it's not a blocker or broken for me, just ... inconvenient 😅. I don't like having to configure rules differently from presets (it's extra space in oftentimes-already-crowded ESLint configs; new users often don't know to do that). But 🤷 this isn't a common use case for me and not something I feel very passionate about.
