### ISSUE TITLE
vitest/expect-expect shouldn't require assertions for bench

### ISSUE THREAD

**Issue by stevezhu** [veritem/eslint-plugin-vitest#367]
Benchmark tests shouldn't require `expect`.

Reference: https://vitest.dev/guide/features.html#benchmarking-experimental

Test: https://github.com/veritem/eslint-plugin-vitest/blob/37c18b4d8656e73d746eed4a02e6e665358541d3/tests/no-standalone-expect.test.ts#L15

**Comment by veritem** [comment]
a pr is welcome
