### ISSUE TITLE
Feature request: formatting rules

### ISSUE THREAD

**Issue by adbayb** [veritem/eslint-plugin-vitest#376]
Hello 👋,

First of all, thanks for porting Jest rules 💪.

To what extent including formatting rules (such as the padding ones implemented [here](https://github.com/dangreenisrael/eslint-plugin-jest-formatting)) could make sense for this plugin?

**Comment by veritem** [comment]
I haven't used Jest formulating rules, but if it's something more people are interested in, I'd consider implementing it.
