### ISSUE TITLE
Invalid flat config

### ISSUE THREAD

**Issue by swachter** [veritem/eslint-plugin-vitest#378]
Configuring the plugin by
```
// eslint.config.js
import vitest from 'eslint-plugin-vitest';

export default [
  vitest.configs.recommended
];
```
results in the following error:
```
ESLint: 8.56.0


A config object has a "plugins" key defined as an array of strings.

Flat config requires "plugins" to be an object in this form:

    {
        plugins: {
            vitest: pluginObject
        }
    }

```
I think the issue is caused by the [createConfig](https://github.com/veritem/eslint-plugin-vitest/blob/main/src/index.ts#L55) function. A possible workaround it to tweak the returned config object in the following way:
```
export default [
  { ...vitest.configs.recommended, plugins: { vitest } }
];
```

**Comment by tobiasdiez** [comment]
Yes, the plugin needs some changes to work with flat configs, see https://eslint.org/docs/latest/extend/plugin-migration-flat-config#migrating-configs-for-flat-config.

**Comment by veritem** [comment]
@tobiasdiez a pr is welcome!

**Comment by veritem** [comment]
@tobiasdiez did you try this?

```ts
import vitest from "eslint-plugin-vitest";

export default [
  {
    files: ["tests/**"], // or any other pattern
    plugins: {
      vitest,
    },
    rules: {
      ...vitest.configs.recommended.rules,
    },
    languageOptions: {
      globals: {
        ...vitest.environments.env.globals,
      },
    },
  },
];
```

**Comment by Stanzilla** [comment]
```
rules: {
      ...vitest.configs.recommended.rules,
    },
 ```
 
 this part errors on 0.4.2-beta.1, Configuration for rule "plugins" is invalid. Expected severity of "off", 0, "warn", 1, "error", or 2.

You passed '"vitest"'.
