### ISSUE TITLE
`expect-expect` fails even if `expectTypeOf` is present

### ISSUE THREAD

**Issue by mrmckeb** [veritem/eslint-plugin-vitest#382]
This may be intentional, but we have some tests that only check types and these are being flagged for failing to include `expect` statements.

**Comment by mrmckeb** [comment]
I should note that I'm happy to make a PR for this if you want the help!

**Comment by veritem** [comment]
@mrmckeb a pr is always welcome :D

**Comment by mrmckeb** [comment]
So thinking about this, and these checks don't actually run unless Vitest is run with `--typecheck` or the `typecheck` config option is set.

Perhaps a rule is also required that warns you if you're using these assertions, but haven't enabled that option in your config?

**Comment by veritem** [comment]
When designing the rule. I did not include the edge case for types. What you'll have todo is it checking if `expectTypeOf ` exists and returning--exiting the rule.

**Comment by mrmckeb** [comment]
Understood, thanks! I have a bit of rule-writing experience so that should be fine.

My concern was more, should this be the default behaviour? If you don't have `typecheck` enabled in your config, then this is the same as having no expects at all.
https://vitest.dev/api/expect-typeof

I can consider that in the work I do though, thanks! :)

**Comment by veritem** [comment]
Definitely,  look into a way of knowing whether `--typecheck` has been enabled and then enable the condition.

**Comment by mrmckeb** [comment]
Done! Thanks again.
