### ISSUE TITLE
Please provide non-flat config

### ISSUE THREAD

**Issue by moltar** [veritem/eslint-plugin-vitest#423]
I think having flat config only is a bit hostile to the users.

Many, if not most, can't upgrade to ESLint 9, because many other plugins might not yet be compatible.

I think for a while, plugins shall provide both versions, and deprecate when the majority of common used plugins have migrated.

I understand it can be a burden to support both, and if that's the motivation, then please disregard my ask.

Thanks!

**Comment by veritem** [comment]
@moltar please install version [0.4.1](https://www.npmjs.com/package/eslint-plugin-vitest/v/0.4.1) you'll be fine!

**Comment by moltar** [comment]
That's what I have now. But I wanted to receive updates. The ESLint migration saga will probably go on for a year.

**Comment by Stanzilla** [comment]
yeah please reconsider that decision

**Comment by Makeshift** [comment]
Additionally, if you are going to release a breaking change, please bump the major version.

**Comment by veritem** [comment]
can anyone on this thread confirm with me that the latest version works using

```js
{
  "extends": ["plugin:vitest/legacy-recommended"] // or legacy-all
}

```

**Comment by moltar** [comment]
Works on a large repo with ~ 60 packages.
