### ISSUE TITLE
vitest/no-conditional-tests rule work not correctly

### ISSUE THREAD

**Issue by neymanushka** [veritem/eslint-plugin-vitest#46]
```
it('some test ', () => {
    const value1 = 1;
    const value2 = 2;
    expect(value1 === 1 && value2 === 2).toBeTruthy();
});
```
error:
```Avoid using conditionals in a test```

**Comment by veritem** [comment]
This behaves correctly for me; there is a better for of writing this, right?

What was your desired behavior in this scenario? I'm closing this but reopen if your feel not satisfied with the rules output
