### ISSUE TITLE
Publish v0.6.0 to NPM

### ISSUE THREAD

**Issue by davecardwell** [veritem/eslint-plugin-vitest#466]
I was keen to check out the fix for #329 (thank you!), but it looks like `v0.6.0` was [tagged](https://github.com/veritem/eslint-plugin-vitest/releases/tag/v0.6.0) but not published to NPM yet.

Please could you publish?

**Comment by davecardwell** [comment]
@veritem Thank you!

**Comment by rentalhost** [comment]
For now this worked for me:

`"eslint-plugin-vitest": "github:veritem/eslint-plugin-vitest#semver:^0.6"`

**Comment by CxRes** [comment]
Can you please start checking in `./dist` to this or another repo while you do not have npm access?

Alternatively, publish it on jsr.io!

**Comment by lishaduck** [comment]
> Can you please start checking in `./dist` to this or another repo while you do not have npm access?

Please don't check in dist. Put it in another repo.

> Alternatively, publish it on jsr.io!

That would be nice.

**Comment by erunion** [comment]
👋 any updates on this?

**Comment by veritem** [comment]
I haven't heard back from npm/gitHub support since June, and I don't know anyone who works there.  still waiting...

**Comment by joel-daros** [comment]
If you didn’t receive any answer in months I don’t think anyone will answer you anyway. In your position I’ll start thinking in creating another account and publish it as a different name.

**Comment by meduzen** [comment]
> In your position I’ll start thinking in creating another account and publish it as a different name.

I second this. Last year I try to reach the support to help someone at work, we never received any answer.

**Comment by tianyingchun** [comment]
oh, just fork, and temporary publish    "eslint-plugin-vitest-2": "^0.6.1" , wait you npm account

**Comment by Sparticuz** [comment]
Is there anything that can be done? There really isn't a way to use the latest version of this package right now.

**Comment by Stanzilla** [comment]
Agree, a new version would be very welcome, especially with the TSESLint peer dep fixed.

**Comment by meduzen** [comment]
> oh, just fork, and temporary publish "eslint-plugin-vitest-2": "^0.6.1" , wait you npm account

That’s what @veritem did: https://www.npmjs.com/package/eslint-plugin-vitest-2

It works on my side (do not forget to add the `-2` to your `package.json` and your ESLint config file.)

**Comment by veritem** [comment]
@meduzen that package does not belong to me.

**Comment by CxRes** [comment]
@meduzen It is Yingchun Tian @tianyingchun who is forked the package to https://www.npmjs.com/package/eslint-plugin-vitest-2 on npm. Given @veritem 's issues with their npm account, I think this is a reasonable stop-gap solution and gives us access to the latest version.

**Comment by veritem** [comment]
I have moved on guys!

```
npm install eslint-plugin-vitest-latest
```

open an issue if something breaks

**Comment by veritem** [comment]
We can a new home guys 

```sh
npm install @vitest/eslint-plugin --save
```

**Comment by Sparticuz** [comment]
Woah, even better, congrats!

**Comment by tianyingchun** [comment]
My own project has switched to the new version and works fine，@hyperse/eslint-config-hyperse
