### ISSUE TITLE
`vitest/no-skipped-tests` does not work if you use `test` instead of `it`

### ISSUE THREAD

**Issue by marcus13371337** [veritem/eslint-plugin-vitest#48]
It seems as the `vitest/no-skipped-test` doesnt work if you use `test` instead of `it` in your test files

**Comment by vitalets** [comment]
The same issue

**Comment by veritem** [comment]
would you mind sharing a repro for this?

**Comment by vitalets** [comment]
> would you mind sharing a repro for this?

To repro the behavior you can add `test.skip` to [plugin tests for no-skipped-tests rule](https://github.com/veritem/eslint-plugin-vitest/blob/838f7ca2cc2f1bed65228e8ba5cb8b3257cea116/src/rules/no-skipped-tests.test.ts#L8):
```diff
const invalids = [
+       'test.skip("test", () => {});',
        'it.skip("test", () => {});',
```

In the codebase of plugin [there are explicitly](https://github.com/veritem/eslint-plugin-vitest/blob/838f7ca2cc2f1bed65228e8ba5cb8b3257cea116/src/rules/no-skipped-tests.ts#L29) `it` and `describe`, but not `test` indentifiers.

**Comment by vitalets** [comment]
Thank you!
