### ISSUE TITLE
Export vitest globals

### ISSUE THREAD

**Issue by goosewobbler** [veritem/eslint-plugin-vitest#50]
It would be nice if this plugin also exported vitest globals so that there's no need to install two different plugins for vitest, e.g. [`eslint-plugin-vitest-globals`](https://github.com/saqqdy/eslint-plugin-vitest-globals).

I'll try to submit a PR for this if / when I have time.

**Comment by veritem** [comment]
Will for sure add it soon; thanks for pointing it out.

**Comment by veritem** [comment]
hello @goosewobbler would you mind giving latest version a quick test and see it it works like you'd like?

**Comment by goosewobbler** [comment]
I'm using flat config but realised that I don't need the globals anyway as I'm importing them from vitest directly, e.g.

```
import { vi, describe, beforeEach, afterEach, it, expect } from 'vitest';
```

Thanks for the recommended ruleset though

**Comment by veritem** [comment]
I thought I added globals as you've request them. Would you mind firing a PR? I don't get exactly what you mean.

**Comment by goosewobbler** [comment]
These ones: https://github.com/saqqdy/eslint-plugin-vitest-globals/blob/master/index.js#L11

**Comment by orept** [comment]
Worked after adding to config:
```
...
plugins: [..., 'vitest'],
env: {
    ...
    'vitest/env': true,
  },
```

**Comment by camsteffen** [comment]
That should be in the readme.

**Comment by veritem** [comment]
@camsteffen can you share whole config? I would like to have a look.

**Comment by camsteffen** [comment]
Sure, this should be a complete example.

```javascript
module.exports = {
  plugins: ["vue", "vitest"],
  env: {
    browser: true,
    es2021: true,
  },
  extends: [
    "eslint:recommended",
  ],
  overrides: [
    { files: ".eslintrc.cjs", env: { node: true } },
    { files: "vite.config.js", env: { node: true } },
    {
      files: "**/*.test.js",
      extends: "plugin:vitest/recommended",
      env: {
        "vitest/env": true,
      },
    },
  ],
};
```

**Comment by command-tab** [comment]
After much trial and error, I discovered that this plugin does not expose Vitest globals to ESLint by default. (Which was counter to my expectations. It's unclear to me why this isn't the default, given the circumstances that one is using both tools.)

To achieve what's detailed above but using the ESLint 9.x+ flat config format, I had to add the following:

```js
languageOptions: {
  globals: {
    ...vitest.environments.env.globals,
  },
},
```

In my case I was also migrating from a standalone ESLint config to one managed by `@nuxt/eslint` which better integrates with Nuxt 3.x, so my whole `eslint.config.mjs` now looks something like this:

```js
import withNuxt from './.nuxt/eslint.config.mjs'
import vitest from '@vitest/eslint-plugin'

export default withNuxt(
  {
    plugins: {
      vitest
    },
    languageOptions: {
      globals: {
        ...vitest.environments.env.globals,
      },
    },
    rules: {
      ...vitest.configs.recommended.rules,
      'vue/no-v-html': 'off',
      // etc.
    },
  }
)
```
