### ISSUE TITLE
Feature Request: force test file name pattern

### ISSUE THREAD

**Issue by trim21** [veritem/eslint-plugin-vitest#57]
rule to perfer `*.spec.*` or `*.test.*`

And I have time to send a Pull Request if you think it's a useful rule.

**Comment by veritem** [comment]
Oooh nice, PRs are always welcome.

**Comment by trim21** [comment]
> Oooh nice, PRs are always welcome.

how should I format codes? I run `pnpm format` but almost all files changed.

**Comment by veritem** [comment]
do `pnpm lint:js`
